name: Deploy to GitHub Pages

on:
  push:
    branches: ['master']
    paths:
      - 'docs/**'

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug
        run: ls -R docs

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        working-directory: docs
        run: npm install --prefix docs --global-style

      - name: Build website
        working-directory: docs
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
